<a href="https://colab.research.google.com/github/lohith-kandibanda/Machine_learning_subj/blob/main/lab-session-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def count_vowels_consonants(Inp_Str):
    vowel_count = 0
    consonant_count = 0
    str = Inp_Str.lower()
    for char in str:
        if char in {'a', 'e', 'i', 'o', 'u'}:
            vowel_count +=1
        elif char in {'b', 'c', 'd', 'f', 'g', 'h' , 'j' , 'k' , 'l', 'm', 'n', 'p', 'q', 'r', 's', 't' , 'v', 'w' , 'x' , 'y' , 'z'}:
            consonant_count +=1
    return (vowel_count, consonant_count)

str = input("enter a string")
v , c = count_vowels_consonants(str)
print(v,c)



enter a stringAbcdefGHIJKlmnopQrstuvwxyz
5 21


In [ ]:
import numpy as np
def Product_AB(A, B):
   return np.dot(A,B)

print("enter the size of row of matrice 1")
r1 = int(input())
print("enter the size of column of matrice 1")
c1 = int(input())
print("enter the size of row of matrice 2")
r2 = int(input())
print("enter the size of column of matrice 2")
c2 = int(input())
matrice1 = []
matrice2 = []
print('enter')
for j in range(r1):
  a = []
  for i in range(c1):
    a.append(int(input()))

  matrice1.append(a)
print('enter')
for j in range(r2):
  a = []
  for i in range(c2):
    a.append(int(input()))
  matrice2.append(a)
if(c1==r2):
  print(Product_AB(matrice1, matrice2))
else:
  print("error")



enter the size of row of matrice 1
3
enter the size of column of matrice 1
3
enter the size of row of matrice 2
3
enter the size of column of matrice 2
3
enter
1
2
3
1
2
3
1
2
3
enter
1
2
3
1
2
3
1
2
3
[[ 6 12 18]
 [ 6 12 18]
 [ 6 12 18]]


In [ ]:
def common_elements(lst1, lst2):
  count = 0
  for i in lst1:
    if i in lst2:
      count += 1
  return count

print("enter the len of lsts")
n = int(input())
lst1 = []
lst2 = []
print("enter the elements of list1")
for i in range(n):
  a = int(input("enter"))
  lst1.append(a)
print("enter the elements of list2")
for i in range(n):
  b = int(input("enter"))
  lst2.append(b)
c = common_elements(lst1,lst2)
print("common elements in lists are ",c)


enter the len of lsts
4
enter the elements of list1
enter1
enter2
enter3
enter4
enter the elements of list2
enter1
enter2
enter3
enter4
common elements in lists are  4


In [ ]:
import numpy as np
def transpose(A):

  np_matrix = np.array(A)
  transposed = np_matrix.T
  return transposed


print("enter the size of row of matrice 1")
r1 = int(input())
print("enter the size of column of matrice 1")
c1 = int(input())
matrice1 = []
print('enter')
for j in range(r1):
  a = []
  for i in range(c1):
    a.append(int(input()))

  matrice1.append(a)
B = transpose(matrice1)
print(B)

enter the size of row of matrice 1
3
enter the size of column of matrice 1
3
enter
1
2
3
2
4
5
7
5
2
[[1 2 7]
 [2 4 5]
 [3 5 2]]
